DELETE http://localhost:3003/api/blogs/64db1f0ac672d8d1fa8405b9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2NGQ5Y2FmNDZmMTcxZDQyY2E0MGRiMmMiLCJpYXQiOjE2OTIwODE5NDAsImV4cCI6MTY5MjA4NTU0MH0.wwqA6_KZa9vMosbuaIvHmSSZl0CywR-TS7mu_BrqkDE
