GET http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpdWtrbyIsImlkIjoiNjU0NjNhNTJjYjgxYzg1ZDA4NDYzNmJhIiwiaWF0IjoxNjk5MTAyMDAyLCJleHAiOjE2OTkxMDU2MDJ9.kxkm3vE5Ortf0SdSA2khvodynUmsVuFYVcmOZPR4kEg


